title: Chris Kim
logo: "/images/logo.png?raw=true"
description: >
  MS Analytics candidate @ Georgia Institute of Technology<br>
  BA Chemistry with a minor in Mathematics @ Manhattan College<br>
  AS Chemistry @ Bergen Community College<br>

  <a href="https://www.linkedin.com/in/christopher-daehyun-kim/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
