title: Chris Kim
logo: "/images/logo.png?raw=true"
description: >
  About Me 
  <br>
  MS Analytics candidate @ Georgia Institute of Technology
  BA Chemistry with minor in Mathematics @ Manhattan College
  AS Chemistry @ Bergen Community College
  <br>
  Interests
  <br>
  My cat Novy
  <br>
  <a href="https://www.linkedin.com/in/christopher-daehyun-kim/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
