title: Chris Kim
logo: "/images/logo.png?raw=true"
description: >
  MS Analytics candidate @ Georgia Institute of Technology<br>
  BA Chemistry with a minor in Mathematics @ Manhattan College<br>
  AS Chemistry @ Bergen Community College<br>
  <br>
  Interests
  <br>
  My cat Novy<br>
  <img src="images/novy.png?raw=true"/><br>
  <br>
  <a href="https://www.linkedin.com/in/christopher-daehyun-kim/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
